version: "3.7"

services:
  ssh:
    image: maestro021/sshserver
    ports:
      - 2222:22
    environment:
      sshuser: sshuser
      password: 1234567
    volumes:
      - /home/data1/:/data/
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager

  samba:
    image: maestro021/samba
    ports:
      - 139:139
      - 145:145
    environment:
      smbuser: smbuser
      password: 1234567
    volumes:
      - /home/data/:/data/
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager

  service1:
    image: maestro021/swarmtest:dotnet
    networks:
      - net1
    volumes:
      - vol1:/d1/
      - vol2:/d2/
      - vol3:/d3/
    ports:
      - 8085:8085
    
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 150MB
        reservations:
          cpus: "0.25"
          memory: 50MB
      restart_policy:
        condition: on-failure
  
  service2:
    image: maestro021/swarmtest:node
    networks:
      - net2
    volumes:
      - vol1:/d1/
      - vol2:/d2/
      - vol3:/d3/
    ports:
      - 8086:8085
    
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 150MB
        reservations:
          cpus: "0.25"
          memory: 50MB
      restart_policy:
        condition: on-failure

networks:
  net1:
  net2:
    driver: overlay
    name: www-net2

volumes:
  vol1:
    driver: local
    name: v1 
    driver_opts:
      type: none
      device: "/home/"
      o: bind
  vol2:
    driver: local
    name: v2
    driver_opts:
      type: cifs
      device: //172.16.10.100/data
      o: "username=smbuser,password=1234567,file_mode=0777,dir_mode=0777"
  vol3:
    driver: vieux/sshfs
    name: v3
    driver_opts:
      sshcmd: "sshuser@172.16.10.100:/data/"
      port: 2222
      password: 1234567
      allow_other: ""